import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Check, ShieldCheck, Building2, ChartNoAxesCombined, Handshake, MapPin, Plus, Instagram } from 'lucide-react';
import { Brand } from '@/components/brand';
import { brand } from '@/lib/brand';

const solutions = [
  { n: '01', icon: ChartNoAxesCombined, title: 'Seu Simples, bem acompanhado.', text: 'Rotina contábil e fiscal organizada, obrigações em dia e clareza para tomar decisões.', tag: 'Gestão contábil' },
  { n: '02', icon: Building2, title: 'Uma nova fase para sua empresa.', text: 'Da abertura à transição do MEI, orientação para escolher os próximos passos com segurança.', tag: 'Abertura e transição' },
  { n: '03', icon: Handshake, title: 'Troque de contador com tranquilidade.', text: 'Um processo de transição acompanhado de perto, respeitando o momento do seu negócio.', tag: 'Migração contábil' },
];
const faqs = [
  ['Minha empresa precisa ser do Simples Nacional?', 'Este portal é voltado a empresas do Simples Nacional e a quem deseja avaliar esse regime. Se você ainda é MEI, está abrindo uma empresa ou tem dúvidas sobre seu enquadramento, conte sua situação no diagnóstico.'],
  ['Como funciona o diagnóstico?', 'Você preenche um breve formulário sobre sua empresa e seu principal desafio. Nossa equipe analisa as informações, entra em contato e orienta os próximos passos.'],
  ['O atendimento é apenas em Vitória?', 'Nosso escritório fica em Vitória, Espírito Santo, e o atendimento digital permite acompanhar empresas em todo o Brasil.'],
  ['Quanto custa a contabilidade?', 'A proposta é personalizada conforme a atividade, o porte e as necessidades da sua empresa. Primeiro entendemos seu cenário; depois apresentamos o escopo e os valores.'],
  ['Preciso enviar documentos agora?', 'Não. Nesta primeira etapa, pedimos apenas informações iniciais para entender sua necessidade. Os documentos necessários serão solicitados pela equipe durante o atendimento.'],
];

export default function Home() {
  return <>
    <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
    <div className="topline"><span>De Vitória para todo o Brasil.</span><span>Contabilidade próxima. Negócios mais fortes.</span></div>
    <header className="site-header"><div className="container nav"><Brand /><nav aria-label="Principal"><a href="#solucoes">Soluções</a><a href="#como-funciona">Como funciona</a><a href="#sobre">Sobre nós</a></nav><Link className="button small" href="/diagnostico">Vamos conversar <ArrowUpRight size={16}/></Link></div></header>
    <main id="conteudo">
      <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span/> ESPECIALISTAS EM SIMPLES NACIONAL</div><h1>Seu negócio<br/>cresce. A gente<br/>cuida do <em>simples.</em></h1><p>Menos dúvidas com a contabilidade.<br className="desktop"/> Mais espaço para o que você faz de melhor.</p><Link href="/diagnostico" className="button">Quero uma orientação <ArrowUpRight size={20}/></Link><div className="hero-assurance"><ShieldCheck size={17}/><span>Atendimento humano. Proposta feita para você.</span></div></div>
      <div className="hero-visual photo-hero"><div className="office-frame"><img src="/brand/escritorio.png" className="hero-office" alt="Recepção do escritório Maurício Rocha Contabilidade em Vitória" fetchPriority="high"/><span className="hero-location"><MapPin size={15}/> VITÓRIA, ESPÍRITO SANTO</span></div><div className="hero-contact-card"><div className="hero-contact-heading"><span className="card-icon"><ShieldCheck size={23}/></span><span>SEU NEGÓCIO<br/>EM BOAS MÃOS.</span></div><h2>Um novo capítulo.<br/>Um começo simples.</h2><p>Conte seu momento.<br/>A gente cuida do próximo passo.</p><Link className="button full" href="/diagnostico">Começar meu diagnóstico <ArrowUpRight size={17}/></Link></div><span className="hero-photo-caption">PROXIMIDADE QUE VOCÊ SENTE.<br/>CONFIANÇA QUE SE CONSTRÓI.</span></div></div></section>
      <div className="trust-strip container"><div><strong>15+</strong><span>anos de experiência<br/>em contabilidade</span></div><div><MapPin/><span>Presença em Vitória.<br/><b>Atendimento nacional.</b></span></div><div><Handshake/><span>Tecnologia que aproxima.<br/><b>Pessoas que resolvem.</b></span></div></div>
      <section id="solucoes" className="section container"><div className="section-heading"><div><span className="eyebrow">A CONTABILIDADE ACOMPANHA VOCÊ</span><h2>Cada fase pede<br/>o cuidado certo.</h2></div><p>Seu negócio tem uma história própria.<br/>Nossa orientação também precisa ter.</p></div><div className="solution-grid">{solutions.map(s=><Link key={s.n} href={`/diagnostico?interesse=${encodeURIComponent(s.tag)}`} className="solution-card"><div className="solution-top"><s.icon size={28}/><span>{s.n}</span></div><span className="tag">{s.tag}</span><h3>{s.title}</h3><p>{s.text}</p><span className="text-link">Conversar sobre minha empresa <ArrowUpRight size={18}/></span></Link>)}</div></section>
      <section id="como-funciona" className="process-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">SEM COMPLICAÇÃO, DESDE O INÍCIO</span><h2>Uma conversa que abre<br/>novas possibilidades.</h2></div><Link href="/diagnostico" className="button outline">Dar o primeiro passo <ArrowUpRight size={18}/></Link></div><div className="process-grid">{[['01','Você conta','Preencha o diagnóstico com o momento da sua empresa e o que precisa resolver.'],['02','A gente escuta','Nossa equipe analisa seu cenário e conversa com você sobre as prioridades.'],['03','Planejamos juntos','Você recebe uma proposta personalizada, com um escopo claro para seu negócio.'],['04','Seguimos por perto','Com tudo alinhado, começa uma parceria para acompanhar sua empresa.']].map(([n,t,d])=><div className="process-item" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
      <section id="sobre" className="section container about-grid"><div className="about-photos"><div className="founder-photo"><img src="/brand/mauricio-rocha.png" alt="Maurício Rocha no escritório de contabilidade" loading="lazy"/><div className="founder-caption"><strong>Maurício Rocha</strong><span>Proximidade em cada etapa.</span></div></div><div className="office-detail-photo"><img src="/brand/escritorio-detalhe.png" alt="Detalhes da estrutura e da marca no escritório Maurício Rocha" loading="lazy"/></div><div className="experience-stamp"><strong>15+</strong><span>ANOS AO LADO<br/>DE QUEM EMPREENDE</span></div></div><div className="about-copy"><span className="eyebrow">PROXIMIDADE PARA IR MAIS LONGE</span><h2>Números importam.<br/>Pessoas, ainda mais.</h2><p>Há mais de 15 anos, a Maurício Rocha Contabilidade acompanha empresários com atendimento personalizado e uma visão prática dos desafios de cada negócio.</p><p>Unimos organização, orientação e presença para que você tenha clareza sobre sua empresa, em cada etapa do caminho.</p><ul>{['Atendimento direto e personalizado','Especialização em Simples Nacional','Soluções conectadas à sua realidade'].map(t=><li key={t}><Check size={18}/>{t}</li>)}</ul><Link className="text-link" href="/diagnostico">Conheça uma contabilidade mais próxima <ArrowUpRight size={19}/></Link></div></section>
      <section className="section faq-section container"><div><span className="eyebrow">PODE PERGUNTAR</span><h2>Clareza desde<br/>a primeira conversa.</h2><p>Algumas respostas antes<br/>do nosso primeiro contato.</p></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
      <section className="container closing"><div><span className="eyebrow">SEU PRÓXIMO CAPÍTULO</span><h2>Vamos simplificar<br/>o futuro da sua empresa?</h2><p>O primeiro passo é a gente se conhecer.</p></div><Link href="/diagnostico" className="button cream">Solicitar proposta personalizada <ArrowUpRight size={20}/></Link></section>
    </main><footer className="site-footer container"><div className="footer-top"><Brand/><p>{brand.address}<br/>{brand.city}</p><div className="footer-contact"><a href={`mailto:${brand.email}`}>{brand.email}</a><span>{brand.phoneLabel}</span><a href={brand.instagram} target="_blank" rel="noreferrer"><Instagram size={15}/> @contabilidade.mauriciorocha</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {brand.company}</span><div><Link href="/privacidade">Privacidade</Link><Link href="/cliente">Área do cliente</Link><Link href="/admin">Área da equipe <ArrowUpRight size={13}/></Link></div></div></footer>
  </>;
}
