'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Building2, Check, CheckCheck, FileText, LogOut, RefreshCw, ShieldCheck, MessageCircle, Clock3 } from 'lucide-react';
import { Brand } from './brand';
import type { ClientView } from '@/lib/client-view';
import { brand, whatsappLink } from '@/lib/brand';
export function ClientPortal(){
  const [data,setData]=useState<ClientView|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [tab,setTab]=useState('overview');const [leaving,setLeaving]=useState(false);
  async function load(){try{const response=await fetch('/api/client',{cache:'no-store'});if(response.status===401){window.location.assign('/admin/login');return;}const result=await response.json();if(!response.ok)throw new Error(result.error);setData(result.client);setError('');}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar seu acompanhamento.');}finally{setLoading(false);}}
  useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},20000);return()=>clearInterval(timer);},[]);
  async function logout(){setLeaving(true);try{const r=await fetch('/api/auth',{method:'DELETE'});if(!r.ok)throw new Error('Não foi possível sair. Tente novamente.');window.location.assign('/admin/login');}catch(e){setError(e instanceof Error?e.message:'Não foi possível sair.');setLeaving(false);}}
  const step=data?['Novo','Em conversa','Proposta enviada','Cliente fechado'].indexOf(data.status):-1;
  return <div className="client-portal"><header className="client-header"><div className="container"><Brand light/><div><span>ÁREA DO CLIENTE</span><button onClick={logout} disabled={leaving}><LogOut size={17}/>{leaving?'Saindo…':'Sair'}</button></div></div></header><main className="container client-main"><div className="client-welcome"><div><span className="eyebrow">SUA EMPRESA, BEM ACOMPANHADA</span><h1>Olá{data?`, ${data.name.split(' ')[0]}`:''}.<br/>Vamos cuidar do próximo passo.</h1><p>Seu atendimento e sua proposta, com clareza em cada etapa.</p></div><button className="button outline small" onClick={()=>void load()}><RefreshCw size={16}/> Atualizar</button></div><nav className="client-tabs" aria-label="Área do cliente">{[['overview','Meu acompanhamento'],['diagnosis','Meu diagnóstico'],['proposal','Minha proposta']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {error&&<div className="error-box" role="alert">{error}</div>}{loading&&<div className="loading">Preparando seu acompanhamento…</div>}
  {data&&<>{data.demo&&<div className="demo-banner"><ShieldCheck size={17}/><span>Área de demonstração. Empresa, diagnóstico e valores fictícios para testar a experiência do cliente.</span></div>}
  <div className="client-layout"><section>{tab==='overview'&&<><div className="panel client-progress"><span className="eyebrow">DO DIAGNÓSTICO À PARCERIA</span><h2>{data.status==='Cliente fechado'?'Uma nova parceria começa aqui.':data.status==='Proposta enviada'?'Sua proposta está pronta.':data.status==='Arquivado'?'Atendimento encerrado.':'Estamos acompanhando seu negócio.'}</h2><p>{data.status==='Proposta enviada'?'Confira os serviços e as condições preparados para sua empresa.':'Você pode acompanhar aqui o andamento do seu atendimento.'}</p><ol>{[['Diagnóstico recebido','Conhecemos o seu momento.'],['Conversa com a equipe','Entendemos as suas prioridades.'],['Proposta personalizada','Um plano pensado para você.'],['Início da parceria','Seguimos por perto.']].map(([title,description],i)=><li key={title} className={i<=step?'complete':''}><span>{i<step?<Check size={17}/>:i+1}</span><div><strong>{title}</strong><p>{description}</p></div>{i===step&&<small>Você está aqui</small>}</li>)}</ol>{data.proposal&&<button className="button small" onClick={()=>setTab('proposal')}>Ver minha proposta <ArrowUpRight size={17}/></button>}</div><div className="client-summary"><Building2 size={24}/><div><strong>{data.company}</strong><p>{data.sector} · {data.regime}</p></div><span>{data.status}</span></div></>}
  {tab==='diagnosis'&&<div className="panel client-diagnosis"><span className="eyebrow">O QUE VOCÊ COMPARTILHOU</span><h2>Seu ponto de partida.</h2><dl>{[['Empresa',data.company],['Contato',data.name],['E-mail',data.email],['Área de atuação',data.sector],['Regime atual',data.regime],['Faturamento mensal',data.revenue]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="challenge-box"><span>SEU PRINCIPAL DESAFIO</span><h3>{data.challenge}</h3><p>{data.details||'Nenhuma observação adicional.'}</p></div><p className="client-note">Precisa corrigir alguma informação? Fale com nossa equipe.</p></div>}
  {tab==='proposal'&&<div className="panel client-proposal">{data.proposal?<><div className="client-proposal-top"><FileText size={27}/><span className="tag">{data.demo?'PROPOSTA DE EXEMPLO':'PROPOSTA PERSONALIZADA'}</span></div><span className="eyebrow">PREPARADA PARA {data.company.toUpperCase()}</span><h2>O cuidado que sua<br/>empresa precisa.</h2><h3>Serviços incluídos</h3><p className="proposal-text">{data.proposal.scope}</p><div className="proposal-price"><div><span>HONORÁRIOS MENSAIS</span><strong>{new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(data.proposal.amount)}</strong></div><CheckCheck size={31}/></div>{data.proposal.notes&&<><h3>Condições e observações</h3><p className="proposal-text">{data.proposal.notes}</p></>}<button className="button outline small client-print" onClick={()=>window.print()}><FileText size={16}/> Imprimir / salvar PDF</button></>:<div className="empty-state"><Clock3 size={32}/><h2>Sua proposta está a caminho.</h2><p>Assim que a equipe compartilhar a proposta, ela aparecerá aqui.</p></div>}</div>}
  </section><aside className="panel client-support"><span className="client-support-icon"><MessageCircle size={27}/></span><h2>Tem alguém<br/>do outro lado.</h2><p>Nossa equipe está por perto para esclarecer suas dúvidas e conversar sobre o seu negócio.</p><div className="client-contact"><strong>{brand.company}</strong><span>{brand.phoneLabel}</span></div>{data.demo?<div className="notice">Nesta conta de teste, o contato externo está desativado.</div>:<a className="button full" href={whatsappLink(`Olá! Sou ${data.name}, da ${data.company}. Estou acompanhando meu atendimento pelo portal e gostaria de conversar.`)} target="_blank" rel="noreferrer">Falar com a equipe <ArrowUpRight size={17}/></a>}<small><ShieldCheck size={15}/> Seus dados ficam na sua área privada.</small></aside></div></>}
  </main><footer className="container client-footer"><span>© {new Date().getFullYear()} {brand.company}</span><Link href="/privacidade">Privacidade</Link></footer></div>;
}
