'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowLeft, ArrowRight, Check, ShieldCheck, CheckCheck, MessageCircle, Building2 } from 'lucide-react';
import { Brand } from './brand';
import { revenues, sectors } from '@/lib/types';
import { whatsappLink } from '@/lib/brand';
import { leadInput } from '@/lib/validation';

const steps=['Seu contato','Sua empresa','Seu momento'];
export function Diagnosis(){
  const search=useSearchParams();const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);const [id,setId]=useState('');
  const form=useRef<HTMLFormElement>(null); const heading=useRef<HTMLHeadingElement>(null);
  const [values,setValues]=useState({name:'',email:'',phone:'',company:'',cnpj:'',sector:'Serviços',revenue:'Até R$ 30 mil',regime:'Simples Nacional',challenge:'Organizar minha contabilidade',details:'',consent:false,website:''});
  useEffect(()=>{setId(crypto.randomUUID());},[]);
  useEffect(()=>{heading.current?.focus();},[step,done]);
  const set=(name:string,value:string|boolean)=>setValues(v=>({...v,[name]:value}));
  async function submit(event:FormEvent){
    event.preventDefault();setError('');
    if(step<2){
      if(step===0 && !/^\+?[\d\s().-]{10,25}$/.test(values.phone)){setError('Informe seu WhatsApp com DDD.');return;}
      setStep(s=>s+1);return;
    }
    const data={...values,submissionId:id,source:search.get('utm_source')||search.get('origem')||'Site',campaign:search.get('utm_campaign')||search.get('interesse')||''};
    const checked=leadInput.safeParse(data);if(!checked.success){setError(checked.error.issues[0].message);return;}
    setBusy(true);
    try{const response=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error);setDone(true);}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar. Tente novamente.');}finally{setBusy(false);}
  }
  return <div className="diagnosis-page"><header className="container form-header"><Brand/><Link href="/" className="text-link"><ArrowLeft size={16}/> Voltar ao site</Link></header><main className="container diagnosis-layout"><aside className="diagnosis-aside"><span className="eyebrow">UM BOM COMEÇO</span><h1>Vamos conhecer<br/>o seu negócio.</h1><p>A melhor orientação começa<br/>com uma boa conversa.</p><div className="form-steps">{steps.map((s,i)=><div className={`${step===i&&!done?'active':''} ${step>i||done?'completed':''}`} key={s}><span>{step>i||done?<Check size={17}/>:i+1}</span><div><small>ETAPA 0{i+1}</small><strong>{s}</strong></div></div>)}</div><div className="aside-note"><ShieldCheck size={24}/><p>Suas informações serão usadas para entender sua necessidade e entrar em contato com você.</p></div></aside>
    <div className="diagnosis-surface">{done?<div className="success-state"><div className="success-icon"><CheckCheck size={35}/></div><span className="eyebrow">PRIMEIRO PASSO CONCLUÍDO</span><h2 ref={heading} tabIndex={-1}>Pronto, {values.name.split(' ')[0]}.<br/>Vamos conversar!</h2><p>Recebemos seu diagnóstico. Nossa equipe vai analisar as informações e entrar em contato pelo WhatsApp informado.</p><div className="receipt"><span>Protocolo do diagnóstico</span><strong>MR-{id.slice(0,8).toUpperCase()}</strong><small>{values.company} · {values.challenge}</small></div><a href={whatsappLink(`Olá! Sou ${values.name}, da ${values.company}. Preenchi o diagnóstico do portal. Meu protocolo é MR-${id.slice(0,8).toUpperCase()}. Gostaria de conversar sobre ${values.challenge.toLowerCase()}.`)} className="button full" target="_blank" rel="noreferrer">Continuar pelo WhatsApp <MessageCircle size={18}/></a><Link href="/" className="text-link">Voltar para o início <ArrowRight size={16}/></Link></div>:
    <form ref={form} onSubmit={submit}><div className="form-step-top"><span className="tag">ETAPA {step+1} DE 3</span><span>Diagnóstico inicial</span></div><h2 ref={heading} tabIndex={-1}>{['Primeiro, como podemos\nfalar com você?','Agora, um pouco\nsobre sua empresa.','O que você precisa\nresolver hoje?'][step]}</h2><p className="form-intro">{['Um contato direto para cuidar do que importa.','Essas informações ajudam a entender o seu cenário.','Conte seu principal desafio. Vamos pensar juntos.'][step]}</p>
    <div className="form-fields">{step===0&&<><Field label="Seu nome" required><input autoComplete="name" required minLength={3} maxLength={100} value={values.name} onChange={e=>set('name',e.target.value)} placeholder="Como você gosta de ser chamado?"/></Field><Field label="E-mail" required><input type="email" autoComplete="email" required maxLength={180} value={values.email} onChange={e=>set('email',e.target.value)} placeholder="voce@empresa.com.br"/></Field><Field label="WhatsApp com DDD" required><input type="tel" autoComplete="tel" required minLength={10} maxLength={25} value={values.phone} onChange={e=>set('phone',e.target.value)} placeholder="(27) 99999-9999"/></Field><div className="form-tip"><MessageCircle size={17}/><span>A equipe vai usar esse número para conversar com você.</span></div></>}
    {step===1&&<><Field label="Nome da empresa" required><input required minLength={2} maxLength={160} value={values.company} onChange={e=>set('company',e.target.value)} placeholder="Nome fantasia ou nome do seu projeto"/></Field><Field label="CNPJ (opcional)"><input maxLength={20} value={values.cnpj} onChange={e=>set('cnpj',e.target.value)} placeholder="Se já tiver, informe seu CNPJ"/></Field><div className="fields-row"><Field label="Área de atuação"><select value={values.sector} onChange={e=>set('sector',e.target.value)}>{sectors.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Regime atual"><select value={values.regime} onChange={e=>set('regime',e.target.value)}>{['Simples Nacional','MEI','Outro regime','Ainda vou abrir','Não sei informar'].map(v=><option key={v}>{v}</option>)}</select></Field></div><Field label="Faturamento mensal aproximado"><select value={values.revenue} onChange={e=>set('revenue',e.target.value)}>{revenues.map(v=><option key={v}>{v}</option>)}</select></Field></>}
    {step===2&&<><Field label="Seu principal desafio"><select value={values.challenge} onChange={e=>set('challenge',e.target.value)}>{['Organizar minha contabilidade','Trocar de contador','Abrir uma empresa','Sair do MEI','Regularizar pendências','Entender meus impostos'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Quer contar mais alguma coisa? (opcional)"><textarea rows={4} maxLength={2000} value={values.details} onChange={e=>set('details',e.target.value)} placeholder="Dúvidas, pendências ou planos para sua empresa…"/></Field><label className="consent"><input type="checkbox" required checked={values.consent} onChange={e=>set('consent',e.target.checked)}/><span>Autorizo a Maurício Rocha Contabilidade a entrar em contato sobre este diagnóstico e li a <Link href="/privacidade" target="_blank">Política de Privacidade</Link>.</span></label></>}
    <div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off" value={values.website} onChange={e=>set('website',e.target.value)}/></label></div></div>
    {error&&<div role="alert" className="error-box">{error}</div>}<div className="form-actions">{step>0?<button type="button" className="text-button" onClick={()=>{setStep(s=>s-1);setError('');}} disabled={busy}><ArrowLeft size={16}/> Voltar</button>:<span className="muted form-required">* Campos obrigatórios</span>}<button className="button" disabled={busy||!id}>{busy?'Enviando…':step===2?'Enviar meu diagnóstico':'Continuar'}<ArrowRight size={18}/></button></div></form>}
    </div></main><footer className="container form-footer"><span><Building2 size={14}/> Maurício Rocha Contabilidade</span><Link href="/privacidade">Privacidade e cuidado com seus dados</Link></footer></div>;
}
function Field({label,children,required=false}:{label:string;children:React.ReactNode;required?:boolean}){return <label className="field"><span>{label}{required&&' *'}</span>{children}</label>;}
