'use client';
import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { ArrowRight, LockKeyhole, Eye, EyeOff, ShieldCheck } from 'lucide-react';
import { Brand } from './brand';
export function Login(){
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [show,setShow]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const values=new FormData(e.currentTarget);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:values.get('email'),password:values.get('password')})});const result=await r.json();if(!r.ok)throw new Error(result.error);window.location.assign(result.redirect === '/cliente' ? '/cliente' : '/admin');}catch(e){setError(e instanceof Error?e.message:'Falha no acesso. Tente novamente.');}finally{setBusy(false);}}
  return <main className="login-page"><div className="login-story"><Brand light/><div><span className="eyebrow">RELACIONAMENTOS QUE CRESCEM</span><h1>Cada conversa,<br/>uma nova<br/><em>possibilidade.</em></h1><p>Um espaço para clientes e equipe<br/>acompanharem cada próximo passo.</p></div><span className="login-sign">mr.</span><small>Maurício Rocha Contabilidade · Portal de relacionamento</small></div><div className="login-main"><Link className="text-link" href="/">Voltar ao site <ArrowRight size={16}/></Link><div className="login-form"><div className="card-icon"><LockKeyhole size={24}/></div><span className="eyebrow">BEM-VINDO DE VOLTA</span><h2>Tudo mais próximo.<br/>Tudo em um só lugar.</h2><p>Entre com seu e-mail e senha. O portal abre a área correspondente ao seu acesso.</p><form onSubmit={submit}><label className="field"><span>E-mail de acesso</span><input type="email" name="email" autoComplete="username" required placeholder="Seu e-mail de acesso"/></label><label className="field"><span>Senha</span><div className="password-input"><input type={show?'text':'password'} name="password" autoComplete="current-password" required maxLength={200} placeholder="Digite sua senha"/><button type="button" aria-label={show?'Ocultar senha':'Mostrar senha'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{error&&<div className="error-box" role="alert">{error}</div>}<button disabled={busy} className="button full">{busy?'Entrando…':'Entrar no painel'}<ArrowRight size={18}/></button></form><small><ShieldCheck size={15}/> Área do cliente e painel da equipe, com acessos separados.</small></div><div className="login-bottom">Problemas para entrar? Fale com o administrador do portal.</div></div></main>;
}
